# Listar todos los usuarios
GET http://localhost:8080/mascotas/all

###

# Crear un usuario

POST http://localhost:8080/mascotas/add
Content-Type: application/x-www-form-urlencoded

nombre=jose
&raza=PastorAleman
&propietario=Rodolfo

###
# Editar usuario

PUT http://localhost:8080/mascotas/edit
Content-Type: application/x-www-form-urlencoded

id=53
&nombre=Lucas
&raza=poodle
&propietario=Luis

###

# Ver usuario por ID
GET http://localhost:8080/mascotas/ver/54

###

# Borrar usuario por ID
DELETE http://localhost:8080/mascotas/del
Content-Type: application/x-www-form-urlencoded

id=102

###

# Ver resultado de una query SQL
GET http://localhost:8080/mascotas/get/report